### ISSUE TITLE
privacy api

### ISSUE THREAD

**Issue by danmarsden** [Limekiller/moodle-block_openai_chat#3]
Moodle uses a privacy API for GDPR compliance to allow plugins to specify how they deal with user data. 
Your plugin interacts with an external API and so correct implementation of a privacy api class is a requirement for approval in the plugins db.

You may get away with using the null privacy provider, however you should take careful note of the external_link_location component of the privacy api - if any user information (username/email/firstname/lastname etc) is passed from Moodle to the external API you must include this information in the external_link_location api.

Sites that use continuous integration processes will not be able to use your plugin because Moodle runs unit tests which check to see if all extra plugins include the privacy class.

More information on the privacy class is here:
https://docs.moodle.org/dev/Privacy_API

**Comment by Limekiller** [comment]
I'm marking this as fixed per https://github.com/Limekiller/moodle-block_openai_chat/commit/84e10fe404b6096e76f32e9bc2513511c702c6d2, with the description "The OpenAI Chat block stores no personal user data; nor does it, by default, send personal data to OpenAI. However, chat messages submitted by users are sent in their entirety to OpenAI, and are then subject to OpenAI\'s privacy policy (https://openai.com/api/policies/privacy/), which may store messages in order to improve the API."

No data is stored by this plugin, and the only data sent to OpenAI is the message that the user submits to the chat -- no other information, identifying or otherwise, is sent -- but if the user were to deliberately include personal data in the message, then that _would_ of course get passed to OpenAI, and they do store messages for some amount of time as per their privacy policy. If I need to be more explicit about this with the external_link_location api just let me know and this issue can be re-opened.

**Comment by danmarsden** [comment]
Looks good!
