### ISSUE TITLE
Assistants

### ISSUE THREAD

**Issue by rimacher** [Limekiller/moodle-block_openai_chat#34]
Hello,

Is it possible to add support for the Assistants feature?

**Comment by Limekiller** [comment]
Hi rimacher, I'm planning on releasing a 2.0 version before January 4th (when OpenAI is removing support for the legacy completion API) and this update will include initial support for the Assistants API. Please note that support will be basic, in large part because the API itself is very basic and still in beta. You can follow progress on this on the "release-2.0" branch.
