### ISSUE TITLE
Plugin not working on mobile 

### ISSUE THREAD

**Issue by OkorrDev** [Limekiller/moodle-block_openai_chat#42]
In mobile, when the plugin is placed on the side, and press a key to input text, the block disappears.

![Screenshot_20240124-235129](https://github.com/Limekiller/moodle-block_openai_chat/assets/127960290/84fe32d9-ebc8-4a28-88f8-64c5789f058c)

When plugin is placed under Dashboard,this problem does not exist.

**Comment by Limekiller** [comment]
Hi @OkorrDev , this is unfortunately due to a bug in Moodle itself where the sidebar closes automatically when the on-screen keyboard appears (see https://tracker.moodle.org/browse/MDL-77957).

However, I've put in a JavaScript hack in the latest update that should prevent this from happening and worked in my testing. Can you update to the latest 2.1.2 version in the release-2.1 branch and let me know if this is fixed for you?

**Comment by OkorrDev** [comment]
Thanks Sor,

Will have a look and revert back to you.

**Comment by OkorrDev** [comment]
Bryce,

This plugin is currently on 2.0.1 at Moodle plugins directory. Are you
going to push an update soon?

Regards,
Fezile

**Comment by Limekiller** [comment]
Since the "fix" for this issue is sort of a workaround that could potentially have side-effects, I'd prefer if you could test the update before I push it to the repository for wide release. You can download the GitHub code as a .zip file by navigating to the [release-2.1 branch](https://github.com/Limekiller/moodle-block_openai_chat/tree/release-2.1) clicking the green "Code" button, and choosing "download as .zip." Then you can install it on your Moodle site the same as a plugin you download from the repository.

Let me know if this isn't doable for whatever reason.

**Comment by OkorrDev** [comment]
Thanks Sir,

Will do.

**Comment by OkorrDev** [comment]
Works fine, Bryce, on my side. It also fixed one problem I had with the
current release: the "submit" and "chat" icon buttons were not rendering
completely, only showing a blue and grey background with no arrow and
refresh icons. Just so you know, the error due to the lack of AI payment
connection is still there in this version. I hope you remember to include
the error explanation before the final release.
